### ISSUE TITLE
Does not work on Xcode 12

### ISSUE THREAD

**Issue by L1cardo** [bow-swift/nef-plugin#19]

**Comment by thenags** [comment]
Yup. It really sucks.

**Comment by miguelangel-dev** [comment]
Hi @L1cardo and @TheInventionMaker,

Thanks for informing about that. Currently, we are working on a big refactor to move to pure FP the logic about `nef`plugin -between other features- and we will release it in next weeks. Also, it updates the tool to the last Xcode version.

At this point, and to review it, could you add more information? I have checked it with the [release 2.0.0](https://github.com/bow-swift/nef-plugin/releases/download/2.0.0/nef-installer-v2_0_0.dmg) in macosx 10.15 and Xcode12, and it works fine.

**Comment by thenags** [comment]
Yeah, no problem. I am running MacOS Big Sur Beta 9, the latest version, and nef does not show at all in the editor. In System preferences, I have it enabled as an Xcode extension, but it just doesn't show in the editor tab. I have Xcode 12 (non-beta), but it is not the latest version (For iOS 14.2 I believe)

**Comment by miguelangel-dev** [comment]
Thanks, it seems to be an OS issue; we will test it together with `Big Sur` before to release the next version. Right now, it should work fine on official non-beta versions of OS+Xcode.

> I will let it open, as a reminder, previous releasing nef plugin 3.0

**Comment by L1cardo** [comment]
I am on
macOS Big Sur 11.0 (20A5384c)
Xcode Version 12.0.1 (12A7300)
and nef-plugin does not work, it seems this is an OS issue.

**Comment by miguelangel-dev** [comment]
To give you some updates, it has been fixed in [the refactoring FP](https://github.com/bow-swift/nef-plugin/pull/18) PR, and it is ready merged into master. We will publish a new version soon!
