### ISSUE TITLE
M1 Xcode 13

### ISSUE THREAD

**Issue by SaeedRahmatolahi** [bow-swift/nef-plugin#22]
Looks like the app doesn't work on M1 Device , I can not see the option in the menu however I could see that before , I am not sure its related to M1 or not but in my old Mac every things were ok and I used migration but I checked the app and it's still just for Intel , this can be for Xcode 13 or M1 can you please check it ?

**Comment by miguelangel-dev** [comment]
@SaeedRahmatolahi try the last release [binary](https://github.com/bow-swift/nef-plugin/releases/download/3.1.0/nef-plugin_3_1_0.zip)

**Comment by SaeedRahmatolahi** [comment]
Will you publish it to the app store as well ?

**Comment by miguelangel-dev** [comment]
I do not think so; `nef` depends on unblocked sandbox to execute some commands in unix file system and it is not allowed in App Store. So, only a few commands will be available if we publish it  in AppStore. 

Just for curiosity - why do you want it official published?

**Comment by SaeedRahmatolahi** [comment]
because this is not only me and some people don't want to download the git
version also it will be better for your brand as well because I think in
the future apple may remove the apps which doesn't support ARM

**Comment by miguelangel-dev** [comment]
> because this is not only me and some people don't want to download the git version also it will be better for your brand as well because I think in the future apple may remove the apps which doesn't support ARM

A good point to be an OSS is you can see what is happening under the hood (security reasons). About AppStore, as it limits a lot the functionality of `nef` I do not think it will be updated in short term; anyway I appreciate your comments. 

I will close this issue as it is resolved using this [binary](https://github.com/bow-swift/nef-plugin/releases/download/3.1.0/nef-plugin_3_1_0.zip).
